### ISSUE TITLE
package name doesn't respect foreman conventoin

### ISSUE THREAD

**Issue by cristi1979** [OpenSCAP/foreman-proxy_openscap#5]
Foreman uses for the proxy plugins a naming convention like this: rubygem-smart_proxy_<plugin>

So, instead of rubygem-foreman-proxy_openscapm it should be rubygem-smart_proxy_openscap.

**Comment by isimluk** [comment]
Thanks for report @cristi1979. I wonder, does Foreman upstream have the convention documented somewhere?

**Comment by isimluk** [comment]
I remember, I have decided to name the proxy 'foreman-proxy_openscap' because there were talks on upstream about renaming smart-proxy to foreman proxy. Part of that actually happened. But then the effort stopped for same reason.

Nevertheless, I will rename back to smart_proxy_openscap. What else I can do.

**Comment by cristi1979** [comment]
I don't think they have any documentation regarding the naming. And I presume they don't enforce it also, but the foreman_proxy puppet module is using by default this:

    'RedHat': "rubygem-smart_proxy_${title}",
    'Debian': "ruby-smart-proxy-${title}"

And the other packages are named in a similar fashion, the only one different being openscap.
